### ISSUE TITLE
Operator Broken for OCP4.x

### ISSUE THREAD

**Issue by christianh814** [christianh814/php-pricelist#4]
It seems like the operator doesn't work for OCP 4.x

```
#  oc logs pricelist-operator-6c87c87dd8-5hbgm ansible
error: expected a resource
# oc logs pricelist-operator-6c87c87dd8-5hbgm operator
error: expected a resource
```

**Comment by christianh814** [comment]
Fixed by ac63d8c

**Comment by whowutwut** [comment]
@christianh814  I'm hitting a similar issue right now `oc logs <pod> ansible|operator` return `error: expected a resource` and came across this issue via google, any explanation about what is happening here?  We are not using that replica option  you linked the fix to in our operator yaml,... trying to find more info anywhere I can to fix/debug this.. 

In this current state, i can't get any logs and the operator is not responding to starting the driver when `oc apply  -f <yaml>` ..

**Comment by whowutwut** [comment]
To follow up, I was able to see the logs using `-c operator` , `-c ansible`  so I think I can get further now,  thanks..
